alias c='xclip -selection clipboard'
alias p='xclip -o -selection clipboard'
alias e='echo'
alias gstat='git status'
alias grep='grep --color=auto'
alias g='grep --color=auto'
alias bc='bc -l'
alias diff='colordiff'
alias vims='nvim -S'
alias vim='nvim'
alias vi='nvim'
alias open='xdg-open'
alias x='exit'
alias naut='nautilus --browser --no-desktop'
#alias tmx='tmux attach -t'
alias du='du -hd 1'
alias df='df -h'
alias spotify="spotify --force-device-scale-factor=1.5"
alias screenshot='gnome-screenshot --interactive'
