alias c='xclip -selection clipboard'
alias p='xclip -o -selection clipboard'
alias e='echo'
alias gstat='git status'
alias grep='grep --color=auto'
alias bc='bc -l'
alias diff='colordiff'
alias vims='nvim -S'
alias vim='nvim'
#alias open='xdg-open'
alias x='exit'
alias naut='nautilus --browser --no-desktop'
alias tmx='tmux attach -t'
alias du='du -h'
alias df='df -h'
